### ISSUE TITLE
How to run with pillar

### ISSUE THREAD

**Issue by jaredmdobson** [Galeria-Kaufhof/pillar#18]
Hey Everyone, thank you for working on this project, it is awesome!  👍   I was wondering how to run pillar from Sbt or the command line.  I see you can run it if you install the RPM but the build system i am on is ubuntu.  And when I run java -cp "slf4j-simple.jar:pillar-assembly.jar" de.kaufhof.pillar.cli.App -d "path/to/migrations" -e "prod" initialize "my_keyspace" in my project root directory i get Error: Could not find or load main class de.kaufhof.pillar.cli.App.   I am new to scala and pillar and appreciate your help.  😄

**Comment by el-dom** [comment]
If you want to use pillar from sbt you can use the [plugin](https://github.com/Galeria-Kaufhof/sbt-pillar-plugin)
